module Selenium
  module WebDriver
    class BiDi
      module Cookies
        def add_cookie: (String name, String value) -> Array[Hash[Symbol, String]]

        def remove_cookie: (String name) -> Array[Hash[Symbol, String]]

        def set_cookie_header: (**Hash[Symbol, String | bool | Numeric] args) -> Array[Hash[Symbol, String | bool | Numeric]]
      end
    end
  end
end
