module Selenium
  module WebDriver
    class BiDi
      module Headers
        def add_header: (String name, String value) -> Array[Hash[Symbol, String]]

        def remove_header: (String name) -> Array[Hash[Symbol, String]]
      end
    end
  end
end
