module Selenium
  module WebDriver
    class BiDi
      class InterceptedItem
        @network: untyped

        @request: untyped

        @id: untyped

        attr_reader network: untyped

        attr_reader request: untyped

        def initialize: (untyped network, untyped request) -> void

        def id: () -> untyped
      end
    end
  end
end
