module Selenium
  module WebDriver
    class BiDi
      class SetCookieHeaders
        @set_cookie_headers: untyped

        def initialize: (untyped set_cookie_headers) -> void

        def all: () -> untyped

        def set_cookie_header: (**untyped args) -> untyped

        def []=: (untyped key, untyped value) -> untyped

        def []: (untyped key) -> untyped

        def delete: (untyped key) -> untyped

        def serialize: () -> (::Array[untyped] | untyped)
      end
    end
  end
end
